name: Basic Usage Example

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      docker-inspect: ${{ steps.inspect.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Build and push Docker image
        run: |
          # Your build steps here
          docker build -t myregistry/my-app:latest .
          docker push myregistry/my-app:latest
          
      - name: Inspect Docker image
        id: inspect
        run: |
          INSPECT_RESULT=$(docker inspect myregistry/my-app:latest)
          echo "result=$INSPECT_RESULT" >> $GITHUB_OUTPUT
          
  check-acceptance:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.check.outputs.should-run }}
      reason: ${{ steps.check.outputs.reason }}
    steps:
      - name: Check if acceptance should run
        id: check
        uses: optivem/should-run-acceptance-stage-action@v1
        with:
          acceptance-stage-repo-owner: ${{ github.repository_owner }}
          acceptance-stage-repo-name: ${{ github.event.repository.name }}
          latest-image-inspect-results: '${{ needs.build.outputs.docker-inspect }}'
          acceptance-stage-workflow-name: 'acceptance.yml'
          
  acceptance-tests:
    needs: check-acceptance
    if: needs.check-acceptance.outputs.should-run == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Run acceptance tests
        run: |
          echo "Running acceptance tests..."
          echo "Reason: ${{ needs.check-acceptance.outputs.reason }}"