name: Test Action

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: read
  actions: read

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Test the action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create test timestamp
        id: test-data
        run: |
          # Create current timestamp for testing
          CURRENT_TIME=$(date -u +"%Y-%m-%dT%H:%M:%S.%6NZ")
          echo "timestamp=$CURRENT_TIME" >> $GITHUB_OUTPUT
        
      - name: Test action with force-run enabled
        id: test-force
        uses: ./
        with:
          latest-image-timestamp: '${{ steps.test-data.outputs.timestamp }}'
          acceptance-stage-workflow-name: 'test.yml'
          force-run: 'true'
          
      - name: Verify force-run outputs
        run: |
          echo "Should run: ${{ steps.test-force.outputs.should-run }}"
          if [ "${{ steps.test-force.outputs.should-run }}" != "true" ]; then
            echo "❌ Force run should always return true"
            exit 1
          fi
          echo "✅ Force run test passed"
          
      - name: Test action with normal mode (new image)
        id: test-normal
        uses: ./
        with:
          latest-image-timestamp: '${{ steps.test-data.outputs.timestamp }}'
          acceptance-stage-workflow-name: 'test.yml'
          force-run: 'false'
          
      - name: Verify normal mode outputs
        run: |
          echo "Should run: ${{ steps.test-normal.outputs.should-run }}"
          # Since we're using a current timestamp, it should run (new image)
          if [ "${{ steps.test-normal.outputs.should-run }}" == "true" ]; then
            echo "✅ Normal mode test passed (new image detected)"
          else
            echo "⚠️ Normal mode returned false - this could be expected if no recent workflow runs"
          fi

  test-different-os:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Test on ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Test action on ${{ matrix.os }}
        uses: ./
        with:
          latest-image-timestamp: '2025-10-10T14:34:00.820799895Z'
          acceptance-stage-workflow-name: 'test.yml'
          force-run: 'true'